apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: sensify server deployment
  name: sensify-server
  namespace: sensify
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sensify-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sensify-server
    spec:
      affinity: {}
      containers:
        - name: sensify-server
          image: ghcr.io/pascalbenstrong/sensify:v0.0.1-rc-9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env: []
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: github-credentials-pascal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: sensify-server
  namespace: sensify
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sensify-server
  sessionAffinity: None
  type: ClusterIP
