name: Build ARM Docker Image And Push ghcr.io

on:
  push:
    tags:
      - "v*-prod-[0-9]+"
      - "v*-rc-[0-9]+"
  workflow_dispatch:
    branches: [main]

env:
  TAG_NAME: ${{ github.ref_name }}
  GITHUB_USERNAME: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  DRAFT: false
  PRERELEASE: true
  FLEET_BRANCH: main
  FLEET_CWD: ./fleet
  GIT_CONFIG_USER_EMAIL: 24707044+PascalBenstrong@users.noreply.github.com
  GIT_CONFIG_USER_NAME: github-action-build-image
  PUSH: true

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Convert tag to lowercase
        id: ghcr_tag
        uses: ASzc/change-string-case-action@v5
        with:
          string: ghcr.io/${{ env.REPOSITORY }}:${{ env.TAG_NAME }}

      - name: Build and push Server
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          push: ${{ env.PUSH }}
          tags: ${{ steps.ghcr_tag.outputs.lowercase }}
          file: Dockerfile

  #       - name: Build and push Backend
  #         env:
  #           TAG: ${{ steps.ghcr_tag.outputs.lowercase }}
  #         run: |
  #           docker build . -f Dockerfile -t $TAG
  #           docker push $TAG

  push-fleet-dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.FLEET_BRANCH }}

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.25.2/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          yq --version

      - name: Convert tag to lowercase
        id: ghcr_tag
        uses: ASzc/change-string-case-action@v5
        with:
          string: ghcr.io/${{ env.REPOSITORY }}:${{ env.TAG_NAME }}

      - name: Update Deployment yaml
        working-directory: ${{ env.FLEET_CWD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BACKEND_IMAGE: ${{ steps.ghcr_tag.outputs.lowercase }}
          VERSION: ${{ env.TAG_NAME }}
        run: |
          yq -i 'select(.spec.template.spec.containers[0].name == "sensify-server").spec.template.spec.containers[0].image |= strenv(BACKEND_IMAGE)' ./deployment-server.yml
          commit_msg="DEPLOYING VERSION $VERSION"
          echo $commit_msg
          git config user.email $GIT_CONFIG_USER_EMAIL
          git config user.name $GIT_CONFIG_USER_NAME
          git commit -am "$commit_msg"
          git push
